version: "3.7"
services:
  db:
    image: postgres:13.2-alpine
    container_name: 'spring-batch-postgres-docker'
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-springBatchDemo:/var/lib/postgresql/data
      - ./sql/data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - "32770:5432"
volumes:
  db-springBatchDemo:
